/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'hsl(230 70% 55%)',
        accent: 'hsl(130 70% 55%)',
        bg: 'hsl(230 20% 12%)',
        surface: 'hsl(230 20% 16%)',
        'surface-elevated': 'hsl(230 20% 20%)',
        'text-primary': 'hsl(230 10% 95%)',
        'text-secondary': 'hsl(230 10% 70%)',
        'text-tertiary': 'hsl(230 10% 50%)',
        'border-primary': 'hsl(230 20% 25%)',
        'border-secondary': 'hsl(230 20% 30%)',
        success: 'hsl(130 70% 55%)',
        warning: 'hsl(45 90% 60%)',
        error: 'hsl(0 70% 55%)',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      borderRadius: {
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
      },
      spacing: {
        '0.5': '2px',
        '1.5': '6px',
        '2.5': '10px',
        '3.5': '14px',
        '4.5': '18px',
        '5.5': '22px',
        '6.5': '26px',
        '7.5': '30px',
        '8.5': '34px',
        '9.5': '38px',
        '18': '72px',
        '22': '88px',
        '26': '104px',
        '30': '120px',
      },
      boxShadow: {
        'card': '0 4px 12px hsla(0, 0%, 0%, 0.15)',
        'card-hover': '0 8px 24px hsla(0, 0%, 0%, 0.2)',
        'focus-ring': '0 0 0 3px hsla(130, 70%, 55%, 0.3)',
        'focus-ring-primary': '0 0 0 3px hsla(230, 70%, 55%, 0.3)',
        'inner': 'inset 0 2px 4px hsla(0, 0%, 0%, 0.1)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backdropBlur: {
        'xs': '2px',
      },
    },
  },
  plugins: [],
}
